name: Delivery
on:
  push:
    branches:
    - delivery
  workflow_dispatch: {}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  new_field_ops_version:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
        - 6.0.x
    name: new_field_ops_version
    steps:
    - name: Trigger all customer upgrades to pre-prod
      run: echo "New version of Field Ops is available. Trigger ONE dispatch "
  clean_up:
    name: clean_up
    needs: new_field_ops_version
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: true
      matrix:
        goversion:
        - 1.19.x
        dotnetversion:
        - 6.0.x
        language:
        - dotnet
    steps:
    - name: Clean up any leftovers of the customer deployment
      run: echo "Clean up any leftovers of the customer deployment"
