name: Delivery
on:
  push:
    branches:
    - delivery
  workflow_dispatch: {}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  new_field_ops_version:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
        - 6.0.x
    name: new_field_ops_version
    steps:
    - name: Trigger all customer upgrades to pre-prod
      run: echo "New version of Field Ops is available. Trigger ONE dispatch "
    - name: Deploy pre-prod per customer
      uses: actions/github-script@v5
      with:
        script: |
          const result = await github.rest.actions.createWorkflowDispatch({
            'antondimitrov',
            'GitFlowSample', 
            'workflows/start-new-customer-upgrade.yaml',
            'delivery',
          });
          console.log(result)
