run-name: Resume workflow for ${{inputs.CustomerRepo}} with jobId ${{ inputs.jobId }} triggered by PR ${{inputs.PR}}
on:
  workflow_dispatch:
    inputs:
      jobId:
        description: 'Job Id'
        required: true
      PR:
        description: 'PR'
        required: true
      CustomerRepo:
        description: 'Customer repo'
        required: true
  pull_request:
    types: [closed]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RE_RUN_JOB_ID: ${{ inputs.jobId }}
jobs:
  start_new_job:
    name: "Starting new job"
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Extract job metadata
        uses: actions/github-script@v6
        with:
          script: |
            const title = "${{github.event.pull_request.title}}";
            let result = {};
            title.split("|")[1]
              .split(",")
              .forEach(function(x){
                let a = x.split(":");
                result[a[0]] = a[1];
              });
            
            const a = JSON.stringify(result);
            console.log(a);
            echo a;
 
            
      
        
