run-name: Resume workflow ${{ inputs.jobId }} 
on:
  workflow_dispatch:
    inputs:
      jobId:
        description: 'Job Id'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RE_RUN_JOB_ID: ${{ inputs.jobId }}
jobs:
  start_new_job:
    name: "Starting new job"
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Restarting workflow job
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.reRunJobForWorkflowRun({
                owner: 'antondimitrov',
                repo: 'GitFlowSample',
                job_id: ${{ inputs.jobId }}
            });
      
        
