name: Start customer upgrade
on:
  push:
    branches:
    - master
  workflow_dispatch: {}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
 clean_up:
    name: clean_up
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: true
      matrix:
        goversion:
        - 1.19.x
        dotnetversion:
        - 6.0.x
        language:
        - dotnet
    steps:
    - name: Clean up any leftovers of the customer deployment
      run: echo "Clean up any leftovers of the customer deployment"
      
