run-name: 'Create PR to update ${{ inputs.productName }} for ${{ inputs.customerName }} to version ${{ inputs.version }}'
on:
  workflow_dispatch:
    inputs:
      productName:
        description: 'Product Name'
        required: true
      customerName:
        description: 'Customer Name'
        required: true
      version:
        description: 'Version'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Update ${{ inputs.productName }} for ${{ inputs.customerName }} to version ${{ inputs.version }} 
        run: |
          .\inputs.ps1 "99.99.99"
        shell: pwsh
      - uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Update ${{ inputs.productName }} for ${{ inputs.customerName }} to version ${{ inputs.version }}
          commit-message: "Update ${{ inputs.productName }} for ${{ inputs.customerName }} to version ${{ inputs.version }}"
          branch: "update-${{ inputs.productName }}-${{ inputs.customerName }}-version"
          delete-branch: true
          body: |
            This PR is auto-generated by ${{ github.event.repository.name }}/action/${{ github.action }}/job/${{ github.job }}
            
            ```
            {
              repo: "${{github.event.repository.name}}"
              action_id: "${{github.action}}"
              inputs: ${{toJson(inputs)}}
            }
            ```
