run-name: 'Update ${{ inputs.productName }} for ${{ inputs.customerName }} to version ${{ inputs.version }}'
on:
  workflow_dispatch:
    inputs:
      productName:
        description: 'Product Name'
        required: true
      customerName:
        description: 'Customer Name'
        required: true
      version:
        description: 'Version'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Update ${{ inputs.productName }} for ${{ inputs.customerName }} to version ${{ inputs.version }}',
              ${{ github.event.repository.owner }},
              ${{ github.event.repository.name }},
              head: '${{ github.ref_name }}',
              base: 'delivery',
              body: [
                'This PR is auto-generated by ${{ github.event.repository.name }}/action/${{ github.action }}/job/${{ github.job }}',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });